### ISSUE TITLE
Roadmap 0.9.0

### ISSUE THREAD

**Issue by himself65** [run-llama/LlamaIndexTS#1408]
Here are the issues I'm goona do before release the next version

> This tabel is frequent to update

## Features

- [x] Revamped Workflow https://github.com/run-llama/LlamaIndexTS/pull/1264

## Bugs
- [x] https://github.com/run-llama/LlamaIndexTS/issues/1407
- [x] https://github.com/run-llama/LlamaIndexTS/issues/1396
- [x] https://github.com/run-llama/LlamaIndexTS/issues/1510
- [x] https://github.com/run-llama/LlamaIndexTS/pull/1413
- [x] https://github.com/run-llama/LlamaIndexTS/issues/1515
- [x] https://github.com/run-llama/LlamaIndexTS/issues/456
- [x] https://github.com/run-llama/LlamaIndexTS/issues/1582

## Missing features
- [x] https://github.com/run-llama/LlamaIndexTS/issues/1399
- [x] https://github.com/run-llama/LlamaIndexTS/issues/1122
  - Use `shiki` to parse the code to HTML, then use html node parser (we also need this)

## Documents

- [x] https://github.com/run-llama/LlamaIndexTS/issues/1405
- [x] Migrate the legacy documents (call for community to help)
- [ ] AI search /w llamacloud
  - [x]  https://github.com/run-llama/LlamaIndexTS/pull/1409
  - [ ] retreval sources display

## Chore

- [x] https://github.com/run-llama/LlamaIndexTS/issues/1403
- [x] https://github.com/run-llama/LlamaIndexTS/issues/1587
- [x] https://github.com/run-llama/LlamaIndexTS/pull/1618 

## Upstream

- [x] https://github.com/huozhi/bunchee/pull/590
